name: Test
on: [push]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install mosquitto broker
        run: sudo apt-get install mosquitto
      - name: Install etcd server
        run: sudo apt-get install etcd-server
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Install test requirements
        run: python -m pip install -r tests/requirements.txt
      - name: Test
        run: pytest